version: '3'

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
<<<<<<< HEAD:srcs/Docker-compose.yml
      device: ${HOME}/data/mariadb
=======
      device: /home/oussama/data/mariadb
>>>>>>> c02ec510fa66ade7785c66c600831d159ec9fdd8:srcs/docker-compose.yml
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
<<<<<<< HEAD:srcs/Docker-compose.yml
      device: ${HOME}/data/wordpress
=======
      device: /home/oussama/data/wordpress
>>>>>>> c02ec510fa66ade7785c66c600831d159ec9fdd8:srcs/docker-compose.yml

services:
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build: ./requirements/mariadb/
    ports:
      - 3360:3360
    volumes:
      - mariadb:/var/lib/mysql

  wp:
    container_name: wp
    env_file:
      - .env
    build: ./requirements/wordpress/
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - wordpress:/usr/share/nginx/html

  nginx:
    env_file:
      - .env
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    depends_on:
      - wp
    volumes:
      - wordpress:/usr/share/nginx/html



