version: '3'

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress

networks:
  myapp_net:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build: ./requirements/mariadb/
    ports:
      - 3360:3360
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - myapp_net

  wp:
    container_name: wp
    env_file:
      - .env
    build: ./requirements/wordpress/
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - wordpress:/usr/share/nginx/html
    networks:
      - myapp_net

  nginx:
    container_name: nginx
    env_file:
      - .env
    build: ./requirements/nginx/
    ports:
      - 443:443
    depends_on:
      - wp
    volumes:
      - wordpress:/usr/share/nginx/html
    networks:
      - myapp_net

  nginx_bonus:
    env_file:
      - .env
    container_name: nginx_bonus
    build: ./requirements/bonus/nginx_bonus/
    ports:
      - 80:80
    networks:
      - myapp_net



