version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb/
    ports:
      - 3360:3360
    restart: always
    environment:
      DB_NAME: test123
      DB_PSSWRD: 1234
      DB_USER: oalaoui
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mariadb:/var/lib/mysql

  wp:
    container_name: wp
    build: ./wordpress/
    ports:
      - 9000:9000
    restart: always
    depends_on:
      - mariadb
    environment:
      DB_NAME: test123
      DB_PSSWRD: 1234
      DB_USER: oalaoui
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - wordpress:/usr/share/nginx/html

  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - 443:443
    depends_on:
      - wp
    volumes:
      - wordpress:/usr/share/nginx/html

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/oalaoui-/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oalaoui-/data/wordpress


